### PR TITLE
Update disable-list.txt

### PR DESCRIPTION
**Pull request by bescritt**
Stopped disabling Google Now Launcher, Drive, Sheets
Added rules to disable a nasty bootkit and remove some chinaphone bloat.

### CODE REVIEW

**Comment by jaredsburrows** [comment]
Google now launcher's package name is `com.google.android.launcher`, see here: https://play.google.com/store/apps/details?id=com.google.android.launcher&hl=en. 

I want to remove the quick search box as well as much pre-installed software as possible.

**Comment by bescritt** [comment]
Sorry, should have written: stop crashing Google Now Launcher.
Google Now Launcher crashes without the quicksearchbox, and will not restart on Android 5.1.
Would you like me to re-submit without deleting any lines, just adding the ones I've found?

**Comment by jaredsburrows** [comment]
@bescritt Yeah, I agree to remove the quick search box from the list but can you keep the sheets and drive on the list?

**Comment by bescritt** [comment]
@jaredsburrows I made the requested revisions. Pull at your leisure.

**Comment by jaredsburrows** [comment]
@bescritt Thanks!

**Pull request merged**
